version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-28-alpha
    working_directory: ~/code
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install Docker client
        command: |
          apt-get update && apt-get -y install sudo
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          sudo mv /tmp/docker/* /usr/bin
    - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - run:
        name: MobSF
        command: |
          TARGET_PATH='/app/app-release.apk' docker-compose up --build --exit-code-from scan
workflows:
  version: 2
  workflow:
    jobs:
    - build
